config/routes.rb
Twiddr::Application.routes.draw do
  root :to => 'welcome#index'

  resource :welcome, :only => [:index]

  resources :users, :controller => "users", :only => [:show, :create] do
    resource :password,
      :controller => 'clearance/passwords',
      :only => [:create, :edit, :update]

    resource :confirmation,
      :controller => 'clearance/confirmations',
      :only => [:new, :create]

    resource :follows, :only => [:create]
  end

end

app/models/following.rb
class Following < ActiveRecord::Base
  validates_presence_of :user_id
  validates_presence_of :followed_user_id
  belongs_to :user
  belongs_to :followed_user, :class_name => "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  validates_presence_of :twiddr_name
  has_many :followings

  def follow(another_user)
    self.followings.create(:followed_user_id => another_user.id)
  end

  def follows?(another_user)
    self.followings.exists?(["followed_user_id = ?", another_user])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Authentication
  protect_from_forgery
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_filter :authenticate

  def create
    user = User.find params[:user_id]
    current_user.follow user
    flash[:notice] = "You are now following #{user.twiddr_name}!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/body_class_helper.rb
module BodyClassHelper
  # TODO: move this into a gem/plugin
  def body_class
    qualified_controller_name = controller.controller_path.gsub('/','-')
    "#{qualified_controller_name} #{qualified_controller_name}-#{controller.action_name}"
  end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
  <title>twiddr</title>
  <%= stylesheet_link_tag :flutie, 'screen', :media => 'all', :cache => true %>
  <%= javascript_include_tag "jquery", "jquery-ui", "prefilled_input", "rails", "application", :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body class="<%= body_class %>">
  <div id="header">
    <% if signed_in? -%>
      <%= link_to "Sign out", sign_out_path, :method => :delete %>
    <% else -%>
      <%= link_to "Sign in", sign_in_path %>
    <% end -%>
  </div>
  <%= render :partial => 'shared/flashes' -%>
  <%= yield %>
  <%= render :partial => 'shared/javascript' %>
</body>
</html>

app/views/shared/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%=h value %></div>
  <% end -%>
</div>

app/views/shared/_javascript.html.erb
<%= javascript_include_tag 'jquery', 'jquery-ui', 'prefilled_input',  :cache => true %>
<%= yield :javascript %>

app/views/users/_inputs.html.erb
<%= form.inputs do %>
  <%= form.input :email %>
  <%= form.input :twiddr_name %>
  <%= form.input :password %>
  <%= form.input :password_confirmation, :label => "Confirm password" %>
<% end %>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= semantic_form_for @user do |form| %>
  <%= form.error_messages %>
  <%= render :partial => "/users/inputs", :locals => { :form => form } %>
  <%= form.buttons do %>
    <%= form.commit_button "Sign up" %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.twiddr_name -%></h2>

<div id="profile">
  <div class="twiddr_name"><%= @user.twiddr_name -%></div>
  <div class="email"><%= @user.email -%></div>
  <div class="follow"><%= button_to "Follow #{@user.twiddr_name}", user_follows_path(@user) -%></div>
</div>

app/views/welcome/index.html.erb
<h3>You follow</h3>
<ul>
  <% current_user.followings.each do |following| %>
    <li class="following"><%= following.followed_user.twiddr_name -%></li>
  <% end %>
</ul>